// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React, { useState, useEffect, useRef } from 'react';
import { useOutlet, history } from 'dumi';
import { warning } from 'D:/code/zeroDraw/node_modules/.pnpm/rc-util@5.44.4_react-dom@18.3.1_react@18.3.1/node_modules/rc-util';
import { SiteContext, type ISiteContext } from 'D:/code/zeroDraw/node_modules/.pnpm/dumi@2.4.23_@babel+core@7.29.0_@types+node@20.19.33_@types+react@18.3.28_eslint@8.57.1_pretti_sj7djr26raghmyozw4fqcgwskq/node_modules/dumi/dist/client/theme-api/context.js';
import { components } from '../meta/atoms';
import { locales } from '../locales/config';



const entryExports = {
};

// Static content
const pkg = {"name":"@zeroDraw/docs"};
const historyType = "browser";
const hostname = undefined;
const themeConfig = {"logo":false,"footer":"zeroDraw — 矢量 & 位图绘画引擎","prefersColor":{"default":"light","switch":true},"nprogress":true,"lastUpdated":true,"name":"zeroDraw","nav":[{"title":"使用指南","link":"/docs/guide"}]};
const _2_level_nav_available = true;

export default function DumiContextWrapper() {
  const outlet = useOutlet();
  const [loading, setLoading] = useState(false);
  const prev = useRef(history.location.pathname);

  useEffect(() => {
    return history.listen((next) => {
      if (next.location.pathname !== prev.current) {
        prev.current = next.location.pathname;

        // scroll to top when route changed
        document.documentElement.scrollTo(0, 0);
      }
    });
  }, []);

  const context: ISiteContext = React.useMemo(() => {
    const ctx = {
      pkg,
      historyType,
      entryExports,
      demos: null,
      components,
      locales,
      loading,
      setLoading,
      hostname,
      themeConfig,
      _2_level_nav_available,
    };

    // Proxy do not warning since `Object.keys` will get nothing to loop
    Object.defineProperty(ctx, 'demos', {
      get: () => {
        warning(false, '`demos` return empty in latest version, please use `useDemo` instead.');
        return {};
      },
    });

    return ctx;
  }, [
    pkg,
    historyType,
    entryExports,
    components,
    locales,
    loading,
    setLoading,
    hostname,
    themeConfig,
    _2_level_nav_available,
  ]);

  return (
    <SiteContext.Provider value={context}>
      {outlet}
    </SiteContext.Provider>
  );
}
