// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from 'D:/workSpace/frontend-monorepo/packages/docs/docs/guide/shortcuts.md?type=frontmatter';
import { demoIndex as dmi0 } from 'D:/workSpace/frontend-monorepo/packages/docs/docs/guide/shortcuts.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from 'D:/workSpace/frontend-monorepo/packages/docs/docs/guide/export.md?type=frontmatter';
import { demoIndex as dmi1 } from 'D:/workSpace/frontend-monorepo/packages/docs/docs/guide/export.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from 'D:/workSpace/frontend-monorepo/packages/docs/docs/guide/layers.md?type=frontmatter';
import { demoIndex as dmi2 } from 'D:/workSpace/frontend-monorepo/packages/docs/docs/guide/layers.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from 'D:/workSpace/frontend-monorepo/packages/docs/docs/guide/index.md?type=frontmatter';
import { demoIndex as dmi3 } from 'D:/workSpace/frontend-monorepo/packages/docs/docs/guide/index.md?type=demo-index';
import { frontmatter as fm4, toc as t4 } from 'D:/workSpace/frontend-monorepo/packages/docs/docs/guide/tools.md?type=frontmatter';
import { demoIndex as dmi4 } from 'D:/workSpace/frontend-monorepo/packages/docs/docs/guide/tools.md?type=demo-index';
import { frontmatter as fm5, toc as t5 } from 'D:/workSpace/frontend-monorepo/packages/docs/docs/guide/faq.md?type=frontmatter';
import { demoIndex as dmi5 } from 'D:/workSpace/frontend-monorepo/packages/docs/docs/guide/faq.md?type=demo-index';
import { frontmatter as fm6, toc as t6 } from 'D:/workSpace/frontend-monorepo/packages/docs/docs/guide/ai.md?type=frontmatter';
import { demoIndex as dmi6 } from 'D:/workSpace/frontend-monorepo/packages/docs/docs/guide/ai.md?type=demo-index';
import { frontmatter as fm7, toc as t7 } from 'D:/workSpace/frontend-monorepo/packages/docs/docs/index.md?type=frontmatter';
import { demoIndex as dmi7 } from 'D:/workSpace/frontend-monorepo/packages/docs/docs/index.md?type=demo-index';

export const filesMeta = {
  'docs/guide/shortcuts': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/workSpace/frontend-monorepo/packages/docs/docs/guide/shortcuts.md?type=text'),
  },
  'docs/guide/export': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/workSpace/frontend-monorepo/packages/docs/docs/guide/export.md?type=text'),
  },
  'docs/guide/layers': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/workSpace/frontend-monorepo/packages/docs/docs/guide/layers.md?type=text'),
  },
  'docs/guide/index': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/workSpace/frontend-monorepo/packages/docs/docs/guide/index.md?type=text'),
  },
  'docs/guide/tools': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/workSpace/frontend-monorepo/packages/docs/docs/guide/tools.md?type=text'),
  },
  'docs/guide/faq': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/workSpace/frontend-monorepo/packages/docs/docs/guide/faq.md?type=text'),
  },
  'docs/guide/ai': {
    frontmatter: fm6,
    toc: t6,
    demoIndex: dmi6,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/workSpace/frontend-monorepo/packages/docs/docs/guide/ai.md?type=text'),
  },
  'docs/index': {
    frontmatter: fm7,
    toc: t7,
    demoIndex: dmi7,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/workSpace/frontend-monorepo/packages/docs/docs/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
