// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'D:/code/zeroDraw/node_modules/.pnpm/dumi@2.4.23_@babel+core@7.29.0_@types+node@20.19.33_@types+react@18.3.28_eslint@8.57.1_pretti_sj7djr26raghmyozw4fqcgwskq/node_modules/dumi/theme-default/slots/SearchBar/index.js';
export * from 'D:/code/zeroDraw/node_modules/.pnpm/dumi@2.4.23_@babel+core@7.29.0_@types+node@20.19.33_@types+react@18.3.28_eslint@8.57.1_pretti_sj7djr26raghmyozw4fqcgwskq/node_modules/dumi/theme-default/slots/SearchBar/index.js';
