// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'D:/workSpace/frontend-monorepo/node_modules/.pnpm/dumi@2.4.23_@babel+core@7.29.0_@swc+helpers@0.5.15_@types+node@22.19.10_@types+react@18.3.28__htimx7wjsd6gpoalopyyfox4l4/node_modules/dumi/theme-default/builtins/Badge/index.js';
